[package]
name = "wgpu-render-practice2"
version = "0.1.0"
edition = "2024"

[dependencies]
pollster = "0.3"
cgmath = "0.18"
image = "0.25.6"
glam = "0.27"
anyhow = "1.0"
env_logger = "0.10"
log = "0.4"
wgpu = "26.0.1"
glfw = "*"
glm = "*"
bytemuck = "1.23.2"